### ISSUE TITLE
使用优先级属性后插件疑似停止工作

### ISSUE THREAD

**Issue by FCWYzzr** [DawnNights/py-pcqq#3]
使用优先级之后似乎没反应了，虽然加载照常

**Comment by DawnNights** [comment]
测试的时候似乎没有这个问题...要不加我QQ2224825532具体说明一下？

**Comment by FCWYzzr** [comment]
不用了，我发现错误了……不过我误打误撞给原来的list插件池改写成了插入法排序的deque插件池，要不要contribute以下：P
[change.zip](https://github.com/DawnNights/py-pcqq/files/8310691/change.zip)
