### ISSUE TITLE
08 36 Response Protocol Packet error，这是不能用了吗

### ISSUE THREAD

**Issue by xwlcn** [DawnNights/py-pcqq#6]
08 36 Response Protocol Packet error。另外，国外Linux服务器上面登录二维码获取不了。

![20230517005727](https://github.com/DawnNights/py-pcqq/assets/15356897/70beeb00-b949-42e6-85f3-d9a23003481f)

并不是版本问题，版本过低会提示前往im.qq.com下载，改到最新版本号就提示上面那个（并不是版本号改错了，因为以前我一直运行的程序突然就登不上去了，代码没做任何改动就提示上面那个错误了），这个提示应该是第一次0836组包校验发生了变化。

**Comment by DawnNights** [comment]
啊这，我没太关注诶。不过这才几个月啊怎么又炸了…我比较佛系来着的，暂时没有维护和完善这个项目的想法，建议找找有没有其它的项目。

**Comment by xwlcn** [comment]
@DawnNights 好吧，二维码的问题是0825包服务端ip的问题，在本地用服务器代理抓个包就能解决。不过PC端的协议好像没看到其他开源项目，都是安卓协议，我的需求比较简单只要能登录就行，不想集成那些安卓协议的，功能太复杂不好二次修改。本人比较菜，不会OD找0836的key，看来只能等大佬有时间更新协议了。目前暂时在服务器上用win系统跑，手动抓key和udp的服务端ip出来供web调用了。

**Comment by xwlcn** [comment]
改好了，是`tlv_313`中的`private_bufMacGuid`与`tlv_501`有问题，手动抓了一对固定写死就好了（换个号不行，只能抓包的那个号登录），不知道能用多久。生成跟QQ号码有关，但不知道具体怎么生成的。
